name: Daily timestamp commit

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp file
        run: |
          echo "Last automated update: $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")" > docs/last-updated.md

      - name: Commit and push if changed
        env:
          TZ: UTC
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/last-updated.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(ci): daily timestamp $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
          git push
